sudo: required

language: python

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - wget https://sites.google.com/a/octarine.ai/home/home/appreg/appreg-py-docker
  - chmod 0750 appreg-py-docker
  - ./appreg-py-docker 172.20.0.9 billing
  - docker build -t haimhelman/octarine-python:billing-service .

install:
  -

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push haimhelman/octarine-python:billing-service

script:
  -
