#!/usr/bin/python

import sys
import os
def change_docker_file(app_name, app_secret, authserver_url, demoserver_url):
    with open('Dockerfile', 'r') as file:
        data = file.readlines()
    os.rename('Dockerfile', 'Dockerfile.orig')
    for i in range(len(data)):
        if data[i].startswith('FROM'):
            data[i] = 'FROM haimhelman/octarine-python\n'
    data.append('ENV OCTARINE_APP_NAME="{}"\n'.format(app_name))
    data.append('ENV OCTARINE_APP_SECRET="{}"\n'.format(app_secret))
    data.append('ENV OCTARINE_AUTHSERVER="{}"\n'.format(authserver_url))
    data.append('ENV OCTARINE_SERVER="{}"\n'.format(demoserver_url))
    with open('Dockerfile', 'w') as file:
        file.writelines(data)

if __name__ == '__main__':
    server = sys.argv[1]
    app = sys.argv[2]
    secret = app+'_pass'
    auth = 'http://{}:5000/'.format(server)
    demo = 'http://{}:5001/'.format(server)
    change_docker_file(app, secret, auth, demo)
